# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

tiers_one:
  url:   /tiers/:cvi/one.:sf_format
  param: { module: tiers, action: findOne }
  requirements: { sf_method: get}

tiers_all:
  url:   /tiers/all.:sf_format
  param: { module: tiers, action: findAll }
  requirements: { sf_method: get}

tiers_all_metteur_marche:
  url:   /tiers/metteur-marche/all.:sf_format
  param: { module: tiers, action: findAllMetteurMarche }
  requirements: { sf_method: get}

tiers_all_declarations:
  url:   /tiers/:cvi/all-declarations.:sf_format
  param: { module: tiers, action: findAllDeclarations }
  requirements: { sf_method: get}

tiers_one_and_all_declarations:
  url:   /tiers/:cvi/one-and-all-declarations.:sf_format
  param: { module: tiers, action: findOneAndAllDeclarations }
  requirements: { sf_method: get}

declaration_all:
  url:   /declaration/all.:sf_format
  param: { module: declaration, action: findAll }
  requirements: { sf_method: get}

declaration_all_by_campagne:
  url:   /declaration/:campagne/all-by-campagne.:sf_format
  param: { module: declaration, action: findAllByCampagne }
  requirements: { sf_method: get}


# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
