all:
  is_secure: false
   
creation:
  is_secure: true
  credentials: [compte]
  
modificationOublie:
  is_secure: true
  credentials: [compte]
  
modification:
  is_secure: true
  credentials: [compte]

droits:
  is_secure: true
  credentials: [compte]

personneAjouter:
  is_secure: true
  credentials: [compte]
  
personneModifier:
  is_secure: true
  credentials: [compte]