Vrac:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      acheteur_type: {  }
      acheteur_identifiant: {  }  
      acheteur:
        type: collection
        class: VracAcheteur
        inheritance: _VracTiers
        definition:
          fields:
            raison_sociale: {  }
            siret: {  }
            cvi: {  }
            num_accise: {  }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            telephone: {  }
            email: {  }
            famille: {  }
      vendeur_type: {  }
      vendeur_identifiant: {  }
      vendeur:
        type: collection
        class: VracVendeur
        inheritance: _VracTiers
        definition:
          fields:
            raison_sociale: {  }
            siret: {  }
            cvi: {  }
            num_accise: {  }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            telephone: {  }
            email: {  }
            famille: {  }
      mandataire_identifiant: {  }
      mandataire:
        type: collection
        class: VracMandataire
        inheritance: _VracTiers
        definition:
          fields:
            nom: {  }
            raison_sociale: {  }
            siret: {  }
            carte_pro: {  }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            telephone: {  }
            email: {  }
            famille: {  }
      declaration:
        type: collection
        class: VracDeclaration
        inheritance: _VracNoeud
        definition:
          fields:
            '*':
              #------ Certification ------
              type: collection
              class: VracCertification
              inheritance: _VracNoeud
              definition:
                fields:
                  '*':
                    type: collection
                    class: VracGenre
                    inheritance: _VracNoeud
                    definition:
                      fields:
                        '*':
                          # ------ Appellation ------
                          type: collection
                          class: VracAppellation
                          inheritance: _VracNoeud
                          definition:
                            fields:
                              libelle: {  }
                              libelle_long: { required: false }
                              # ------- MENTION ----------
                              'mention':
                                type : collection
                                class: VracMention
                                inheritance: _VracNoeud
                                definition:
                                  fields:
                                    libelle: {  }
                                    libelle_long: { required: false }
                                    # ------- LIEU ----------
                                    '*':
                                      type: collection
                                      class: VracLieu
                                      inheritance: _VracNoeud
                                      definition:
                                        fields:
                                          libelle: { }
                                          libelle_long: { required: false }
                                          # ------ Couleur ------
                                          '*':
                                            type: collection
                                            class: VracCouleur
                                            inheritance: _VracNoeud
                                            definition:
                                              fields:
                                                libelle: {  }
                                                libelle_long: { required: false }
                                              # ------ Cépage ------
                                                '*':
                                                  type: collection
                                                  class: VracCepage
                                                  inheritance: _VracNoeud
                                                  definition:
                                                    fields:
                                                      libelle: {  }
                                                      libelle_long: { required: false }
                                                      no_vtsgn: {  }
                                                      detail:                                                        
                                                        type: array_collection
                                                        definition:
                                                          fields:
                                                            '*':
                                                              type: collection
                                                              class: VracDetail
                                                              definition:
                                                                fields:
                                                                  vtsgn: { }
                                                                  millesime: { }
                                                                  prix_unitaire: { type: float }
                                                                  denomination: { }
                                                                  solde: { type: integer }
                                                                  volume_propose: { type: float }
                                                                  volume_enleve: { type: float }
                                                                  retiraisons:
                                                                    type: collection
                                                                    definition:
                                                                      fields:
                                                                        '*': { type: float }
                                                                  position: { type: integer }
                                                                  supprimable: { type: integer }
      valide:
        type: collection
        class: VracValide
        definition:
          fields:
            date_saisie: {  }
            date_validation_vendeur: {  }
            date_validation_acheteur: {  }
            date_validation_mandataire: {  }
            date_validation: {  }
            statut: { }
      campagne: {  }
      numero_contrat: {  }
      numero_archive: {  }
      prix_total: { type: float }
      volume_total: { type: float }
      etape: {  }
      type: {  }