DR:
  definition:
    fields:
      _id: {}
      _rev: {}
      type: {}
      campagne: {  }
      updated: { required: false }
      validee: { required: false }
      modifiee: { required: false }
      import_db2: {type: integer, required: false }
      declarant:
        type: collection
        class: DRDeclarant
        definition:
          fields:
            nom: {}
            email: {}
            telephone: {}
      acheteurs:
        type: collection
        class: DRAcheteurs
        definition:
          fields:
          # -------- rappel des appellations -------
            '*':
              type: collection
              definition:
                fields:
                  'negoces':
                    type: array_collection
                    definition: 
                      fields: 
                        '*': {  }
                  'cooperatives':
                    type: array_collection
                    definition: 
                      fields: 
                        '*': {  }
                  'cave_particuliere': {type: integer}
                  'mouts':
                    type: array_collection
                    definition:
                      fields:
                        '*': {  }
      cvi: {  }
      lies: {type: float}
      jeunes_vignes: {type: float}
      declaration_commune: {}
      declaration_insee: {}
      etape: {type: string, required: false}
      recolte:
        type: collection
        class: DRRecolte
        definition:
          fields:
            # ------ Appellation ------
            '*':
              type: collection
              class: DRRecolteAppellation
              definition:
                fields:
                  appellation: {}
                  total_volume: {type: float}
                  total_superficie: {type: float}
                  volume_revendique: {type:float }
                  dplc: {type:float }
                  # ------- LIEU ----------
                  '*':
                    type: collection
                    class: DRRecolteLieu
                    definition:
                      fields:
                        total_volume: {type:float}
                        total_superficie: {type:float}
                        volume_revendique: {type: float}
                        dplc: {type: float}
                        acheteurs: 
                           type: collection
                           definition:
                             fields:
                               negoces:
                                 type: collection
                                 definition:
                                   fields:
                                     '*':
                                       type: collection
                                       class: DRRecolteLieuAcheteur
                                       definition:
                                         fields:
                                           type_acheteur: {}
                                           nom: {}
                                           commune: {}
                                           superficie: {type:float}
                                           dontdplc: {type:float}
                               cooperatives:
                                 type: collection
                                 definition:
                                   fields:
                                     '*':
                                       type: collection
                                       class: DRRecolteLieuAcheteur
                                       definition:
                                         fields:
                                           type_acheteur: {}
                                           nom: {}
                                           commune: {}
                                           superficie: {type:float}
                                           dontdplc: {type:float}
                               mouts:
                                 type: collection
                                 definition:
                                   fields:
                                     '*':
                                       type: collection
                                       class: DRRecolteLieuAcheteur
                                       definition:
                                         fields:
                                           type_acheteur: {}
                                           nom: {}
                                           commune: {}
                                           superficie: {type:float}
                                           dontdplc: {type:float}
                        # ------ Cépage ------
                        '*':
                          type: collection
                          class: DRRecolteCepage
                          definition:
                            fields:
                              total_volume: {type: float }
                              total_superficie: {type:float }
                              volume_revendique: {type:float }
                              dplc: {type:float }
                              detail:
                                type: array_collection
                                definition:
                                  fields:
                                    '*':
                                      type: collection
                                      class: DRRecolteCepageDetail
                                      definition:
                                        fields:
                                          appellation: {  }
                                          cepage: {  }
                                          denomination: {  }
                                          vtsgn: {  }
                                          code_lieu: {  }
                                          volume: { type: float }
                                          superficie: { type: float }
                                          motif_non_recolte: { required: false}
                                          negoces:
                                            type: array_collection
                                            definition:
                                              fields:
                                                '*':
                                                  type: collection
                                                  definition:
                                                    fields:
                                                      cvi: {  }
                                                      quantite_vendue: { type: float }
                                          cooperatives:
                                            type: array_collection
                                            definition:
                                              fields:
                                                '*':
                                                  type: collection
                                                  definition:
                                                    fields:
                                                      cvi: {  }
                                                      quantite_vendue: { type: float }
                                          mouts:
                                            type: array_collection
                                            required: false
                                            definition:
                                              fields:
                                                '*':
                                                  type: collection
                                                  definition:
                                                    fields:
                                                      cvi: {  }
                                                      quantite_vendue: { type: float }
                                          cave_particuliere: { type: float }
                                          volume_revendique: { type: float }
                                          volume_dplc: { type: float }

Acheteur:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      cvi: {  }
      civaba: {  }
      type: {  }
      qualite: {  }
      nom: {  }
      commune: {  }
      achnum: {  }

Tiers:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {  }
      cvi: {  }
      no_declarant: { type: integer, required: false }
      recoltant: { type: integer }
      mot_de_passe: { }
      num: {  }
      no_stock: {  }
      maison_mere: {  }
      regime_fiscal: { }
      civaba: {  }
      no_accises: {  }
      cvi_acheteur: {  }
      declaration_insee: {}
      declaration_commune: {}
      siret: { type: string }
      intitule: {  }
      nom: {  }
      siege:
        type: collection
        class: TiersSiege
        definition:
          fields:
            adresse: {  }
            insee_commune: {  }
            code_postal: { }
            commune: {  }
      telephone: {  }
      fax: {  }
      email: {  }
      web: {  }
      exploitant:
        class: TiersExploitant
        type: collection
        definition:
          fields:
            sexe: {  }
            nom: {  }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            date_naissance: {  }
            telephone: {  }
      metteur_marche:
        type: collection
        required: false
        definition:
          fields:
            nom: {  }
      revision_dernieres_modifications: {required: false}

Configuration:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {}
      dr_non_editable : {required: false}
      intitule:
        type: array_collection
        definition:
          fields:
            '*': {  }
      motif_non_recolte:
        type: collection
        definition:
          fields:
            '*': {  }
      recolte:
        type: collection
        definition:
          fields:
            douane :
              type: collection
              class: ConfigurationDouane
              definition:
                fields:
                  type_aoc: {required: false}
                  couleur: {required: false}
                  appellation_lieu: {required: false}
                  qualite: {required: false}
                  qualite_vt: {required: false}
                  qualite_sgn: {required: false}
                  qualite_aoc: {required: false}
                  code_cepage: {required: false}
            '*':
            # ------- APPELLATION ---------
              type: collection
              class: ConfigurationAppellation
              definition:
                fields:
                  appellation: { }
                  libelle: {  }
                  rendement : { type: float }
                  rendement_appellation: { type: float }
                  mout: {type: integer}
                  no_total_cepage: {type: integer, required: false}
                  exclude_total: {type: integer, required: false}
                  douane :
                    type: collection
                    class: ConfigurationDouane
                    definition:
                      fields:
                        type_aoc: {required: false}
                        couleur: {required: false}
                        appellation_lieu: {required: false}
                        qualite: {required: false}
                        qualite_aoc: {required: false}
                        code_cepage: {required: false}
                  '*':
                  # ------------ LIEU --------------
                    type: collection
                    class: ConfigurationLieu
                    definition:
                      fields:
                        rendement: {type: float}
                        rendement_appellation: { type: float }
                        libelle: {}
                        douane :
                          type: collection
                          class: ConfigurationDouane
                          definition:
                            fields:
                              type_aoc: {required: false}
                              couleur: {required: false}
                              appellation_lieu: {required: false}
                              qualite: {required: false}
                              code_cepage: {required: false}
                        '*':
                        # ------------ CEPAGE -------------
                          type: collection
                          class: ConfigurationCepage
                          definition:
                            fields:
                              no_vtsgn: {required: false}
                              douane :
                                type: collection
                                class: ConfigurationDouane
                                definition:
                                  fields:
                                    type_aoc: {required: false}
                                    couleur: {required: false}
                                    appellation_lieu: {required: false}
                                    qualite: {required: false}
                                    code_cepage: {required: false}
                              libelle: {  }
                              rendement: { type: float }
                              min_quantite: {type: float, required: false}
                              max_quantite: {type: float, required: false}
                              exclude_total: {type: integer, required: false}
                              superficie_optionnelle: { type: integer, required: false }
                              no_negociant : { type: integer, required: false }
                              no_cooperative : { type: integer, required: false }
                              no_mout : { type: integer, required: false }
                              no_motif_non_recolte : { type: integer, required: false }


Messages:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {}
      '*': {}