DR:
  definition:
    fields:
      _id: {}
      _rev: {}
      type: {}
      campagne: {  }
      acheteurs:
        type: collection
        definition:
          fields:
          # -------- rappel des appellations -------
            '*':
              type: collection
              definition:
                fields:
                  'negoces':
                    type: array_collection
                    definition: 
                      fields: 
                        '*': {  }
                  'cooperatives':
                    type: array_collection
                    definition: 
                      fields: 
                        '*': {  }
      cvi: {  }
      lies: {type: float}
      jeunes_vignes: {type: float}
      recolte:
        type: collection
        class: DRRecolte
        definition:
          fields:
            # ------ Appellation ------
            '*':
              type: collection
              class: DRRecolteAppellation
              definition:
                fields:
                  appellation: {}
                  total_volume: {type: float}
                  total_superficie: {type: float}
                  # ------- LIEU ----------
                  '*':
                    type: collection
                    definition:
                      fields:
                        # ------ Cépage ------
                        '*':
                          type: collection
                          class: DRRecolteAppellationCepage
                          definition:
                            fields:
                              total_volume: {type: float }
                              total_superficie: {type:float }
                              volume_revendique: {type:float }
                              dplc: {type:float }
                              detail:
                                type: array_collection
                                definition:
                                  fields:
                                    '*':
                                      type: collection
                                      class: DRRecolteAppellationCepageDetail
                                      definition:
                                        fields:
                                          appellation: {  }
                                          cepage: {  }
                                          denomination: {  }
                                          vtsgn: {  }
                                          code_lieu: {  }
                                          volume: { type: float }
                                          superficie: { type: float }
                                          negoces:
                                            type: array_collection
                                            definition:
                                              fields:
                                                '*':
                                                  type: collection
                                                  class: DRRecolteAppellationCepageDetailAcheteur
                                                  definition:
                                                    fields:
                                                      cvi: {  }
                                                      quantite_vendue: { type: float }
                                          cooperatives:
                                            type: array_collection
                                            definition:
                                              fields:
                                                '*':
                                                  type: collection
                                                  definition:
                                                    fields:
                                                      cvi: {  }
                                                      quantite_vendue: { type: float }
                                          cave_particuliere: { type: float }
                                          volume_revendique: { type: float }
                                          volume_dplc: { type: float }

Acheteur:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      cvi: {  }
      civaba: {  }
      type: {  }
      qualite: {  }
      nom: {  }
      commune: {  }
      achnum: {  }

Recoltant:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {  }
      cvi: {  }
      num: {  }
      no_stock: {  }
      maison_mere: {  }
      civaba: {  }
      no_accises: {  }
      siret: {  }
      intitule: {  }
      nom: {  }
      siege:
        type: collection
        definition:
          fields:
            adresse: {  }
            insee_commune: {  }
            code_postal: { }
            commune: {  }
      telephone: {  }
      fax: {  }
      email: {  }
      web: {  }
      exploitant:
        class: RecoltantExploitant
        type: collection
        definition:
          fields:
            sexe: {  }
            nom: {  }
            adresse: {  }
            code_postal: {  }
            commune: {  }
            date_naissance: {  }
            telephone: {  }

Configuration:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {}
      recolte:
        type: collection
        definition:
          fields:
            '*':
            # ------- APPELLATION ---------
              type: collection
              class: SubConfiguration
              definition:
                fields:
                  libelle: {  }
                  rendement : { type: float }
                  '*':
                  # ------------ LIEU --------------
                    type: collection
                    class: SubConfiguration
                    definition:
                      fields:
                        rendement: {type: float}
                        libelle: {}
                        '*':
                        # ------------ CEPAGE -------------
                          type: collection
                          class: SubConfiguration
                          definition:
                            fields:
                              libelle: {  }
                              rendement: { type: float }
