#schema des DS
DS:
  definition:
    fields:
      _id: {}
      _rev: {}
      type: {}
      identifiant: {}
      date_emission: {}
      date_echeance: {}
      date_stock: {}
      campagne: {}
      periode: {}
      numero_archive: {  }
      statut: {}
      commentaires: {}
      declarant:
        type: collection
        definition:
          fields:
            nom: {  }
            cvi: {  }
            num_accise: {   }
            num_tva_intracomm: {    }
            adresse: {  }
            commune: {  }
            code_postal: {   }
            raison_sociale: {  }
      declarations:
        type: collection
        definition:
          fields:
            '*':
              class: DSProduit
              type: collection
              definition:
                fields:
                  code_douane: {}
                  produit_libelle: {}
                  produit_hash: {}
                  stock_initial: { type: float }
                  stock_revendique: { type: float }
                  vci: { }
                  reserve_qualitative: { }
