# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_RecolteTotale():
    client = WindmillTestClient(__name__)

    client.open(url=u'http://declaration.dev.vinsdalsace.fr/civa_dev.php/')
    client.waits.forPageLoad(timeout=u'8000')
    client.click(id=u'recoltant_cvi')
    client.type(text=u'6823700100', id=u'recoltant_cvi')
    client.click(value=u'Valider')
    client.waits.forPageLoad(timeout=u'8000')
    client.click(link=u'Ann\xe9es pr\xe9c\xe9dentes')
    client.click(xpath=u"//div[@id='precedentes_declarations']/div/ul/li[2]/ul/li/ul/li/a")
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'R\xe9colte totale', timeout=u'8000')
    client.click(link=u'R\xe9colte totale')
    client.click(xpath=u"//div[@id='appelations']/table/tbody/tr[4]/td[1]")
    client.asserts.assertText(xpath=u"//div[@id='appelations']/table/thead/tr/th[2]", validator=u'ALSACEBLANC')

