# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# *********** VRAC ***********
vrac_selection_type:
  url: /vrac/selection-type/:type
  param: { module: vrac, action: selectionType, type: null }
vrac_nouveau:
  url: /vrac/nouveau
  param: { module: vrac, action: nouveau }
vrac_historique:
  url: /vrac/historique
  param: { module: vrac, action: historique }
vrac_export_csv:
  url: /vrac/export/csv
  param: { module: vrac, action: exportCSV }
vrac_soussigne_informations:
  url: /vrac/:numero_contrat/soussignes-informations
  param: { module: vrac, action: soussigneInformations }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_supprimer:
  url: /vrac/:numero_contrat/supprimer
  param: { module: vrac, action: supprimer }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_cloture:
  url: /vrac/:numero_contrat/cloture
  param: { module: vrac, action: cloture }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_fiche:
  url: /vrac/:numero_contrat/fiche
  param: { module: vrac, action: fiche }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_validation:
  url: /vrac/:numero_contrat/fiche/validation
  param: { module: vrac, action: validation }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_export_pdf:
  url: /vrac/:numero_contrat/pdf
  param: { module: vrac_export, action: PDF, odg: 0}
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_export_odg:
  url: /vrac/:numero_contrat/odg
  param: { module: vrac_export, action: PDF, odg: 1}
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_annuaire_commercial:
  url: /vrac/:numero_contrat/annuaire/commercial
  param: { module: vrac, action: annuaireCommercial }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_annuaire:
  url: /vrac/:numero_contrat/annuaire/:acteur/:type
  param: { module: vrac, action: annuaire }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
    allow_empty: true
  requirements:
    sf_method: [get, post]
vrac_etape:
  url: /vrac/:numero_contrat/:etape
  param: { module: vrac, action: etape }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
    allow_empty: true
  requirements:
    sf_method: [get, post]
vrac_ajout_produit:
  url: /vrac/:numero_contrat/:etape/ajouter
  param: { module: vrac, action: ajouterProduit }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_ajout_produit_lieux:
  url: /vrac/:numero_contrat/:etape/ajouter/lieux
  param: { module: vrac, action: ajouterProduitLieux }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_ajout_produit_cepages:
  url: /vrac/:numero_contrat/:etape/ajouter/cepages
  param: { module: vrac, action: ajouterProduitCepages }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]
vrac_ajout_produit_vtsgn:
  url: /vrac/:numero_contrat/:etape/ajouter/vtsgn
  param: { module: vrac, action: ajouterProduitVtsgn }
  class: VracRoute
  options:
    model:    Vrac
    type:     object
  requirements:
    sf_method: [get, post]

telecharger_la_notice_vrac:
  url:   /vrac/telecharger_la_notice
  param: { module: vrac, action: downloadNotice }

# *********** ANNUAIRE *********
annuaire:
  url: /annuaire
  param: { module: annuaire, action: index }
annuaire_retour:
  url: /annuaire/retour
  param: { module: annuaire, action: retour }
annuaire_selectionner:
  url: /annuaire/selectionner/:type
  param: { module: annuaire, action: selectionner, type: null }
annuaire_commercial_ajouter:
  url: /annuaire/ajouter/commercial
  param: { module: annuaire, action: ajouterCommercial }
annuaire_ajouter:
  url: /annuaire/ajouter/:type/:identifiant
  param: { module: annuaire, action: ajouter }
annuaire_supprimer:
  url: /annuaire/supprimer/:type/:id
  param: { module: annuaire, action: supprimer }


# *********** COMPTE ***********
login:
  url:   /
  param: { module: compte, action: login }

login_no_cas:
  url:   /login_no_cas
  param: { module: compte, action: loginNoCas }

logout:
  url:   /logout
  param: { module: compte, action: logout }

compte:
  url: /compte
  param: { module: compte, action: first }

compte_creation:
  url: /compte/creation
  param: { module: compte, action: creation }

compte_modification_oublie:
  url: /compte/mot_de_passe_oublie
  param: { module: compte, action: modificationOublie }

compte_modification:
  url: /mon_compte
  param: { module: compte, action: modification }

compte_mot_de_passe_oublie_login:
  url: /mdpo/login/:login/:mdp
  param: { module: compte, action: motDePasseOublieLogin }

compte_mot_de_passe_oublie:
  url: /mot_de_passe_oublie
  param: { module: compte, action: motDePasseOublie }

compte_mot_de_passe_oublie_confirm:
  url: /mot_de_passe_oublie/confirm
  param: { module: compte, action: motDePasseOublieConfirm }

compte_droits:
  url: /mon_compte/gestion_des_droits
  param: { module: compte, action: droits }

compte_personne_ajouter:
  url: /mon_compte/personne/ajouter
  param: { module: compte, action: personneAjouter }

compte_personne_modifier:
  url: /mon_compte/personne/modifier/:login
  param: { module: compte, action: personneModifier }

# *********** TIERS ***********

tiers:
  url: /tiers
  param: { module: tiers, action: login }

mon_espace_civa:
  url:   /mon_espace_civa
  param: { module: tiers, action: monEspaceCiva }

mon_espace_civa_dr:
  url:   /mon_espace_civa/dr
  param: { module: tiers, action: monEspaceDR }

mon_espace_civa_dr_acheteur:
  url:   /mon_espace_civa/dr_acheteur
  param: { module: tiers, action: monEspaceDRAcheteur }

mon_espace_civa_ds:
  url:   /mon_espace_civa/ds/:type
  param: { module: tiers, action: monEspaceDS }

mon_espace_civa_gamma:
  url:   /mon_espace_civa/gamma
  param: { module: tiers, action: monEspaceGamma }

mon_espace_civa_vrac:
  url:   /mon_espace_civa/vrac
  param: { module: tiers, action: monEspaceVrac }


delegation:
  url: /delegation
  param: { module: tiers, action: delegation}

migration_compte:
  url: /migration_compte
  param: { module: tiers, action: migrationCompte}

dr_notice_evolutions:
  url: /notice_evolutions
  param: { module: declaration, action: noticeEvolutions}
# *********** DECLARATION ***********

declaration_init:
  url:   /declaration/init
  param: { module: declaration, action: init }

declaration_invalider_recoltant:
  url:   /admin/declaration/invalider_recoltant
  param: { module: declaration, action: invaliderRecoltant }

declaration_invalider_civa:
  url:   /admin/declaration/invalider_civa
  param: { module: declaration, action: invaliderCiva }

declaration_autorisation:
  url:   /declaration/autorisation
  param: { module: declaration, action: autorisation }

declaration_transmission:
  url:   /declaration/transmission/:id
  param: { module: declaration, action: transmission }


# *********** GAMMA ***********

gamma:
  url:   /gamma
  param: { module: gamma, action: process }

gamma_telecharger_la_notice:
  url:   /gamma/telecharger_la_notice
  param: { module: gamma, action: downloadNotice }

gamma_telecharger_la_liste_nomenclature:
  url:   /gamma/telecharger_la_liste_nomenclature
  param: { module: gamma, action: downloadNomenclatures }

gamma_telecharger_la_procedure_enlevement_propriete:
  url:   /gamma/telecharger_la_procedure_enlevement_propriete
  param: { module: gamma, action: downloadEnlevementPropriete }

gamma_telecharger_l_adhesion:
  url:   /gamma/telecharger_l_adhesion
  param: { module: gamma, action: downloadAdhesion }

# *********** ADMIN ***********

admin-login:
  url: /admin/login
  param: { module: admin, action: login }

admin-logout:
  url: /admin/logout
  param: { module: admin, action: login }

admin:
  url: /admin
  param: { module: admin, action: index }

admin_gamma:
  url:   /admin/gamma
  param: { module: admin, action: gamma }

admin_back_to_the_future:
  url: /admin_back_to_the_future
  param: { module: admin, action: backToFuture }

admin_back_to_now:
  url: /admin_back_to_now
  param: { module: admin, action: backToNow }

delegate_mode_retour_espace_civa:
   url: /tiers/retour_mon_espace
   param: { module: tiers, action: signoutByCompteDelegue }

# *********** EXPLOITATION ***********
visualisation_avant_import:
  url:   /visualisation_avant_import
  param: { module: declaration, action: visualisationAvantImport }


exploitation_message:
  url:   /exploitation_message
  param: { module: declaration, action: flashPage }


exploitation_administratif:
  url:   /exploitation_administratif
  param: { module: tiers, action: exploitationAdministratif }

exploitation_acheteurs:
  url:   /exploitation_acheteurs
  param: { module: acheteur, action: exploitationAcheteurs }

exploitation_lieu:
  url:   /exploitation_lieu
  param: { module: acheteur, action: exploitationLieu }

exploitation_lieu_delete:
  url:  /exploitation_lieu/delete/:lieu
  param: {module: acheteur, action: exploitationLieuDelete }

  exploitation_lieu_delete:
  url:  /exploitation_lieu/delete/:appellation/:lieu
  param: {module: acheteur, action: exploitationLieuDelete }

exploitation_autres:
  url:   /exploitation_autres
  param: { module: declaration, action: exploitationAutres }

# *********** RECOLTE ***********

recolte:
  url:   /recolte/:appellation_lieu/:couleur_cepage
  param: { module: recolte, action: recolte, appellation_lieu: null,couleur_cepage: null}
  class: sfRouteAnchor

recolte_update:
  url:   /recolte/:appellation_lieu/:couleur_cepage/update/:detail_key
  param: { module: recolte, action: update }
  class: sfRouteAnchor

recolte_delete:
  url:   /recolte/:appellation_lieu/:couleur_cepage/delete/:detail_key
  param: { module: recolte, action: delete }
  class: sfRouteAnchor

recolte_add:
  url:   /recolte/:appellation_lieu/:couleur_cepage/add
  param: { module: recolte, action: add}
  class: sfRouteAnchor

recolte_motif_non_recolte:
  url:   /recolte/:appellation_lieu/:couleur_cepage/:detail_key/motif_non_recolte
  param: { module: recolte, action: motifNonRecolte }
  class: sfRouteAnchor

recolte_add_appellation:
  url:   /recolte/:appellation_lieu/:couleur_cepage/add_appellation
  param: { module: recolte, action: ajoutAppellationAjax }
  class: sfRouteAnchor

recolte_add_lieu:
  url:   /recolte/:appellation_lieu/:couleur_cepage/add_lieu
  param: { module: recolte, action: ajoutLieuAjax }
  class: sfRouteAnchor

recolte_add_acheteur:
  url:   /recolte/:appellation_lieu/:couleur_cepage/add_acheteur
  param: { module: recolte, action: ajoutAcheteurAjax }
  class: sfRouteAnchor

recolte_recapitulatif:
  url:   /recapitulatif/:appellation_lieu
  param: {module: recolte, action: recapitulatif }
  class: sfRouteAnchor

recolte_rendements_max:
  url:   /rendements_max
  param: { module: recolte, action: rendementsMaxAjax}

recolte_erreur_log:
  url:   /recolte_erreur_log
  param: {module: declaration, action: setFlashLog }
  class: sfRouteAnchor

validation:
  url:   /validation
  param: { module: declaration, action: validation }

visualisation:
  url: /visualisation/:annee
  param: {module: declaration, action: visualisation }

confirmation:
  url:   /confirmation
  param: { module: declaration, action: confirmation }

telecharger_la_notice:
  url:   /telecharger_la_notice
  param: { module: declaration, action: downloadNotice }

print:
  url: /print/:annee
  param: {module: export, action: pdf}

send_email_pdf:
  url: /send-email-pdf
  param: {module: declaration, action: sendPdf}
  
send_email_acheteurs_pdf:
  url: /send-email-acheteurs-pdf
  param: {module: declaration, action: sendPdfAcheteurs}
  
recolte_feed_back:
  url: /declaration/retour-experience
  param: {module: declaration, action: feedBack}
  
recolte_feed_back_confirmation:
  url: /declaration/retour-experience-confirmation
  param: {module: declaration, action: feedBackConfirmation}
  
xml:
  url: /xml/:annee
  param: {module: export, action: xml}

csv_comptes:
  url: /comptes/csv
  param: {module: export, action: comptesCSV}

csv_tiers_dr_en_cours:
  url: /tiers/dr-en-cours/csv
  param: {module: export, action: csvTiersDREncours}

export_dr_acheteur_csv:
  url: /acheteur/import/dr/csv
  param: {module: export, action: drAcheteurCsv}

export_dr_validee_csv:
  url: /acheteur/import/utilisateurs/csv
  param: {module: export, action: drValideeCsv}


statistiques:
  url: /statistiques
  param: {module: statistiques, action: index}

message:
  url: /message
  param: {module: global, action: messageAjax}

message_ds:
  url: /message-ds
  param: {module: ds, action: messageAjax}

mentions_legales:
  url: /mentions-legales
  param: {module: contenu, action: mentionsLegales}

contact:
  url: /contact
  param: {module: contenu, action: contact}

a_propos_du_civa:
  url: /a-propos-du-civa
  param: {module: contenu, action: aProposDuCiva}

upload_csv:
  url: /upload/csv
  param: {module: upload, action: monEspaceCiva}

upload_list:
  url: /upload/list
  param: {module: upload, action: csvList}

csv_view:
  url: /upload/csv/:md5
  param: {module: upload, action: csvView}

csv_download:
  url: /download/csv
  param: {module: upload, action: csvDownload}

task_list:
  url: /taches
  param: {module: task, action: list}

task_info:
  url: /taches/:namespace/:slug/infos
  param: {module: task, action: info}
  requirements:
    namespace: '[a-zA-Z0-9_-]+'
    slug: '[a-zA-Z0-9_-]+'

task_run:
  url: /taches/:namespace/:slug/lancer
  param: {module: task, action: run}
  requirements:
    namespace: '[a-zA-Z0-9_-]+'
    slug: '[a-zA-Z0-9_-]+'

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
