monEspaceCiva:
  credentials: []

visualisation:
  credentials: [declarant]

exploitationAutres:
  credentials: [declarant, declaration_brouillon, etape_recolte]

validation:
  credentials: [declarant, declaration_brouillon, etape_validation]

setFlashLog:
  credentials: [declarant, declaration_brouillon, etape_validation]

confirmation:
  credentials: [declarant, declaration_valide]