init:
  credentials: [declaration_en_cours]

visualisation:
  credentials: [declaration]

exploitationAutres:
  credentials: [declaration_etape_recolte]

validation:
  credentials: [declaration_etape_validation]

setFlashLog:
  credentials: [declaration_etape_validation]

confirmation:
  credentials: [declaration_valide]
  
invaliderCiva:
  credentials: [operateur, declaration_valide]
  
invaliderRecoltant:
  credentials: [operateur, declaration_valide]