# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

monEspaceCivaSuccess:
  metas:
    title:        Mon espace civa - Espace des professionnels du Vignoble d’Alsace

exploitationAutresSuccess:
  metas:
    title:        Autres - Déclaration de récolte de %d
    
validationSuccess:
  metas:
    title:        Validation - Déclaration de récolte de %d

confirmationSuccess:
  metas:
    title:        Confirmation - Déclaration de récolte de %d