# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

exploitationAdministratifSuccess:
  metas:
    title:        Administratif - Déclaration de récolte de vins d'alsace