# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  etapes:
    items:
      mon_espace_civa:
        url: "@mon_espace_civa"
        next_is_new_etape: exploitation
      exploitation_administratif:
        url: "@exploitation_administratif"
      exploitation_acheteurs:
        url: "@exploitation_acheteurs"
      exploitation_lieu:
        url: "@exploitation_lieu"
        next_is_new_etape: recolte
      recolte:
        url: "@recolte"
      exploitation_autres:
        url: "@exploitation_autres"
        next_is_new_etape: validation
      validation:
        url: "@validation"
      confirmation:
        url: "@confirmation"
    orders: [mon_espace_civa, exploitation_administratif, exploitation_acheteurs, exploitation_lieu, recolte, exploitation_autres, validation, confirmation]
  css_class_field_error: "erreur"





