# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

  
# *********** COMPTE ***********

login:
  url:   /
  param: { module: compte, action: login }

logout:
  url:   /logout
  param: { module: compte, action: logout }
  
compte:
  url: /compte
  param: { module: compte, action: first }
  
compte_creation:
  url: /compte/creation
  param: { module: compte, action: creation }
  
compte_modification_oublie:
  url: /compte/mot_de_passe_oublie
  param: { module: compte, action: modificationOublie }

compte_modification:
  url: /mon_compte
  param: { module: compte, action: modification }
  
compte_mot_de_passe_oublie_login:
  url: /mot_de_passe_oublie/login/:login/:mdp
  param: { module: compte, action: motDePasseOublieLogin }
  
compte_mot_de_passe_oublie:
  url: /mot_de_passe_oublie
  param: { module: compte, action: motDePasseOublie }
  
compte_mot_de_passe_oublie_confirm:
  url: /mot_de_passe_oublie/confirm
  param: { module: compte, action: motDePasseOublieConfirm }

# *********** TIERS ***********

tiers:
  url: /tiers
  param: { module: tiers, action: login }

mon_espace_civa:
  url:   /mon_espace_civa
  param: { module: tiers, action: monEspaceCiva }

# *********** DECLARATION ***********

declaration_init:
  url:   /declaration/init
  param: { module: declaration, action: init }
  
declaration_invalider_recoltant:
  url:   /admin/declaration/invalider_recoltant
  param: { module: declaration, action: invaliderRecoltant }

declaration_invalider_civa:
  url:   /admin/declaration/invalider_civa
  param: { module: declaration, action: invaliderCiva }


# *********** GAMMA ***********

gamma:
  url:   /gamma
  param: { module: gamma, action: process }
  
gamma_telecharger_la_notice:
  url:   /gamma/telecharger_la_notice
  param: { module: gamma, action: downloadNotice }
  
gamma_telecharger_l_adhesion:
  url:   /gamma/telecharger_l_adhesion
  param: { module: gamma, action: downloadAdhesion }
  
# *********** ADMIN ***********

admin:
  url: /admin
  param: { module: admin, action: index }

admin_gamma:
  url:   /admin/gamma
  param: { module: admin, action: gamma }
  
# *********** EXPLOITATION ***********

exploitation_administratif:
  url:   /exploitation_administratif
  param: { module: tiers, action: exploitationAdministratif }

exploitation_acheteurs:
  url:   /exploitation_acheteurs
  param: { module: acheteur, action: exploitationAcheteurs }

exploitation_lieu:
  url:   /exploitation_lieu
  param: { module: acheteur, action: exploitationLieu }

exploitation_lieu_delete:
  url:  /exploitation_lieu/delete/:lieu
  param: {module: acheteur, action: exploitationLieuDelete }

exploitation_autres:
  url:   /exploitation_autres
  param: { module: declaration, action: exploitationAutres }

# *********** RECOLTE ***********

recolte:
  url:   /recolte/:appellation_lieu/:cepage
  param: { module: recolte, action: recolte, appellation_lieu: null, cepage: null}
  class: sfRouteAnchor

recolte_update:
  url:   /recolte/:appellation_lieu/:cepage/update/:detail_key
  param: { module: recolte, action: update }
  class: sfRouteAnchor

recolte_delete:
  url:   /recolte/:appellation_lieu/:cepage/delete/:detail_key
  param: { module: recolte, action: delete }
  class: sfRouteAnchor

recolte_add:
  url:   /recolte/:appellation_lieu/:cepage/add
  param: { module: recolte, action: add}
  class: sfRouteAnchor

recolte_motif_non_recolte:
  url:   /recolte/:appellation_lieu/:cepage/:detail_key/motif_non_recolte
  param: { module: recolte, action: motifNonRecolte }
  class: sfRouteAnchor

recolte_add_appellation:
  url:   /recolte/:appellation_lieu/:cepage/add_appellation
  param: { module: recolte, action: ajoutAppellationAjax }
  class: sfRouteAnchor

recolte_add_lieu:
  url:   /recolte/:appellation_lieu/:cepage/add_lieu
  param: { module: recolte, action: ajoutLieuAjax }
  class: sfRouteAnchor

recolte_add_acheteur:
  url:   /recolte/:appellation_lieu/:cepage/add_acheteur
  param: { module: recolte, action: ajoutAcheteurAjax }
  class: sfRouteAnchor

recolte_recapitulatif:
  url:   /recapitulatif/:appellation_lieu
  param: {module: recolte, action: recapitulatif }
  class: sfRouteAnchor
  
recolte_rendements_max:
  url:   /rendements_max
  param: { module: recolte, action: rendementsMaxAjax}
  
recolte_erreur_log:
  url:   /recolte_erreur_log
  param: {module: declaration, action: setFlashLog }
  class: sfRouteAnchor

validation:
  url:   /validation
  param: { module: declaration, action: validation, annee: 2010 }

visualisation:
  url: /visualisation/:annee
  param: {module: declaration, action: visualisation }

confirmation:
  url:   /confirmation
  param: { module: declaration, action: confirmation, annee: 2010 }

telecharger_la_notice:
  url:   /telecharger_la_notice
  param: { module: declaration, action: downloadNotice }
  
print:
  url: /print/:annee
  param: {module: export, action: pdf}

send_email_pdf:
  url: /send-email-pdf
  param: {module: declaration, action: sendPdf}

xml:
  url: /xml/:annee
  param: {module: export, action: xml}
  
csv_tiers:
  url: /tiers/csv
  param: {module: export, action: csvTiers}

csv_tiers_dr_en_cours:
  url: /tiers/dr-en-cours/csv
  param: {module: export, action: csvTiersDREncours}

csv_tiers_non_validee_civa:
  url: /tiers/non-validee-civa/csv
  param: {module: export, action: csvTiersNonValideeCiva}

csv_tiers_modifications:
  url: /tiers/modifications/csv
  param: {module: export, action: csvTiersModifications}

csv_tiers_modifications_email:
  url: /tiers/modifications-email/csv
  param: {module: export, action: csvTiersModificationsEmail}
  
export_dr_acheteur_csv:
  url: /acheteur/import/dr/csv
  param: {module: export, action: drAcheteurCsv}
  
statistiques:
  url: /statistiques
  param: {module: statistiques, action: index}

message:
  url: /message
  param: {module: global, action: messageAjax}

mentions_legales:
  url: /mentions-legales
  param: {module: contenu, action: mentionsLegales}

contact:
  url: /contact
  param: {module: contenu, action: contact}
  
a_propos_du_civa:
  url: /a-propos-du-civa
  param: {module: contenu, action: aProposDuCiva}

upload_csv:
  url: /upload/csv
  param: {module: import, action: csvUpload}

csv_view:
  url: /upload/csv/:md5
  param: {module: import, action: csvView}

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
