# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
login:
  url:   /
  param: { module: tiers, action: login }

login_admin:
  url:   /civa-admin
  param: { module: tiers, action: loginAdmin }

logout:
  url:   /logout
  param: { module: tiers, action: logout }

mon_espace_civa:
  url:   /mon_espace_civa
  param: { module: declaration, action: monEspaceCiva }

mon_espace_civa_non_declarant:
  url:   /mon_espace_civa_non_declarant
  param: { module: tiers, action: monEspaceCivaNonDeclarant }

declaration_rendre_editable:
  url:   /declaration/rendre_editable
  param: { module: declaration, action: rendreEditable }

declaration_devalider:
  url:   /declaration/devalider
  param: { module: declaration, action: devalider }

gamma:
  url:   /gamma
  param: { module: tiers, action: gamma }

gamma-admin:
  url:   /gamma-admin
  param: { module: tiers, action: gammaAdmin }

exploitation_administratif:
  url:   /exploitation_administratif
  param: { module: tiers, action: exploitationAdministratif }

exploitation_acheteurs:
  url:   /exploitation_acheteurs
  param: { module: acheteur, action: exploitationAcheteurs }

exploitation_lieu:
  url:   /exploitation_lieu
  param: { module: acheteur, action: exploitationLieu }

exploitation_lieu_delete:
  url:  /exploitation_lieu/delete/:lieu
  param: {module: acheteur, action: exploitationLieuDelete }

exploitation_autres:
  url:   /exploitation_autres
  param: { module: declaration, action: exploitationAutres }

recolte:
  url:   /recolte/:appellation_lieu/:cepage
  param: { module: recolte, action: recolte, appellation_lieu: null, cepage: null}
  class: sfRouteAnchor

recolte_update:
  url:   /recolte/:appellation_lieu/:cepage/update/:detail_key
  param: { module: recolte, action: update }
  class: sfRouteAnchor

recolte_delete:
  url:   /recolte/:appellation_lieu/:cepage/delete/:detail_key
  param: { module: recolte, action: delete }
  class: sfRouteAnchor

recolte_add:
  url:   /recolte/:appellation_lieu/:cepage/add
  param: { module: recolte, action: add}
  class: sfRouteAnchor

recolte_motif_non_recolte:
  url:   /recolte/:appellation_lieu/:cepage/:detail_key/motif_non_recolte
  param: { module: recolte, action: motifNonRecolte }
  class: sfRouteAnchor

recolte_add_appellation:
  url:   /recolte/:appellation_lieu/:cepage/add_appellation
  param: { module: recolte, action: ajoutAppellationAjax }
  class: sfRouteAnchor

recolte_add_lieu:
  url:   /recolte/:appellation_lieu/:cepage/add_lieu
  param: { module: recolte, action: ajoutLieuAjax }
  class: sfRouteAnchor

recolte_add_acheteur:
  url:   /recolte/:appellation_lieu/:cepage/add_acheteur
  param: { module: recolte, action: ajoutAcheteurAjax }
  class: sfRouteAnchor

recolte_recapitulatif:
  url:   /recapitulatif/:appellation_lieu
  param: {module: recolte, action: recapitulatif }
  class: sfRouteAnchor

recolte_erreur_log:
  url:   /recolte_erreur_log
  param: {module: declaration, action: setFlashLog }
  class: sfRouteAnchor

validation:
  url:   /validation
  param: { module: declaration, action: validation, annee: 2010 }

visualisation:
  url: /visualisation/:annee
  param: {module: declaration, action: visualisation }

confirmation:
  url:   /confirmation
  param: { module: declaration, action: confirmation, annee: 2010 }

compte:
  url: /compte
  param: { module: compte, action: index }

mon_compte:
  url: /mon_compte
  param: { module: compte, action: modification }

telecharger_la_notice:
  url:   /telecharger_la_notice
  param: { module: declaration, action: downloadNotice }

telecharger_la_notice_gamma:
  url:   /telecharger_la_notice_gamma
  param: { module: declaration, action: downloadNoticeGamma }

print:
  url: /print/:annee
  param: {module: export, action: pdf}

send_email_pdf:
  url: /send-email-pdf
  param: {module: declaration, action: sendPdf}

xml:
  url: /xml/:annee
  param: {module: export, action: xml}

csv_tiers:
  url: /tiers/csv
  param: {module: export, action: csvTiers}

csv_tiers_dr_en_cours:
  url: /tiers/dr-en-cours/csv
  param: {module: export, action: csvTiersDREncours}

csv_tiers_non_validee_civa:
  url: /tiers/non-validee-civa/csv
  param: {module: export, action: csvTiersNonValideeCiva}

csv_tiers_modifications:
  url: /tiers/modifications/csv
  param: {module: export, action: csvTiersModifications}

csv_tiers_modifications_email:
  url: /tiers/modifications-email/csv
  param: {module: export, action: csvTiersModificationsEmail}

statistiques:
  url: /statistiques
  param: {module: statistiques, action: index}

message:
  url: /message
  param: {module: global, action: messageAjax}

mentions_legales:
  url: /mentions-legales
  param: {module: contenu, action: mentionsLegales}

contact:
  url: /contact
  param: {module: contenu, action: contact}
  
a_propos_du_civa:
  url: /a-propos-du-civa
  param: {module: contenu, action: aProposDuCiva}

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
