default:
  credentials: [tiers]

login:
  credentials: [compte_tiers]

#loginAdmin:
#  credentials: [admin]

exploitationAdministratif:
  credentials: [declaration_etape_exploitation]

#monEspaceCivaNonDeclarant:
#  credentials: [non_declarant]